from app.core.route_contract import FrontendRouteUsage, extract_backend_routes, find_unmatched_frontend_routes


def test_business_phase2_target_routes_are_registered() -> None:
    usages = [
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/parties", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/parties", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/parties/{param}", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "PATCH", "/api/v1/business/parties/{param}", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/parties/{param}/deactivate", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/vouchers", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/vouchers", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/vouchers/{param}", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/vouchers/{param}/review", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/vouchers/{param}/reverse", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/approval-queue", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/ca-documents", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/ca-documents", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "PATCH", "/api/v1/business/ca-documents/{param}", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/ca-clients", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/ca-clients", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/ca-documents/{param}/attachments", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/ca-documents/{param}/attachments", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/ca-documents/{param}/attachments/{param}/download", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/invoices", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/invoices", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/invoices/{param}", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/invoices/{param}/cancel", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/invoices/{param}/attachments", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/invoices/{param}/attachments", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/invoices/{param}/attachments/{param}/download", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/invoice-settings", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "PUT", "/api/v1/business/invoice-settings", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/admin-settings", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "PUT", "/api/v1/business/admin-settings", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/bills", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/bills", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/bills/{param}", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/bills/{param}/cancel", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/bills/{param}/attachments", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/bills/{param}/attachments", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/bills/{param}/attachments/{param}/download", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/gst-period-locks", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "PUT", "/api/v1/business/gst-period-locks", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/credit-notes", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/credit-notes", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/credit-notes/{param}", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/credit-notes/{param}/cancel", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/debit-notes", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/debit-notes", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/debit-notes/{param}", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/debit-notes/{param}/cancel", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/gst-settlement/preview", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/gst-settlement", "phase2-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/gst-settlement/{param}/reverse", "phase3-realstack-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/inventory/items", "phase3-inventory-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/inventory/items", "phase3-inventory-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "PATCH", "/api/v1/business/inventory/items/{param}/deactivate", "phase3-inventory-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/inventory/stock-register", "phase3-inventory-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/inventory/closing-stock/entries", "phase3-inventory-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/inventory/closing-stock", "phase3-inventory-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/bank-recon/statement", "phase3-banking-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/bank-recon", "phase3-banking-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/bank-recon/match", "phase3-banking-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/bank-recon/match/{param}/reverse", "phase3-banking-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/fixed-assets", "phase3-fixed-assets-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/fixed-assets", "phase3-fixed-assets-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/fixed-assets/{param}/dispose", "phase3-fixed-assets-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/depreciation/preview", "phase3-fixed-assets-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/depreciation/run", "phase3-fixed-assets-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/dimensions", "phase3-dimensions-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/dimensions", "phase3-dimensions-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "PATCH", "/api/v1/business/dimensions/{param}/deactivate", "phase3-dimensions-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/dimensions/report", "phase3-dimensions-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/dimensions/report/export", "phase3-dimensions-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/dimensions/branch-report", "phase3-branch-report-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/reports/export", "phase5-export-governance-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/mis/kpis", "phase5-mis-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/data-health", "phase5-data-health-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/returns/gstr-3b", "phase3-realstack-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/returns/gstr-1", "phase3-realstack-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "POST", "/api/v1/business/returns/gstr-2b/reconcile", "phase3-realstack-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/returns/cmp-08", "phase3-realstack-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/returns/gstr-4", "phase3-realstack-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/tds/sections", "phase3-realstack-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/business/tds/register", "phase3-realstack-contract", 1),
        FrontendRouteUsage("MitraBooksERP", "GET", "/api/v1/audit/events", "phase2-contract", 1),
    ]

    unresolved = find_unmatched_frontend_routes(usages, extract_backend_routes())

    assert unresolved == []
