"""
Qualities and properties of Nakshatras and Tithis
"""

from typing import Dict

NAKSHATRA_QUALITIES = {
    "Ashwini": {
        "stars": 4,
        "label": "Auspicious",
        "color": "#4CAF50",
        "deity": "Ashwini Kumaras (Divine Physicians)",
        "nature": "Light (Laghu) - Swift",
        "ruling_planet": "Ketu",
        "element": "Earth",
        "good_for": ["Starting new ventures", "Medical treatments", "Travel and journeys", "Buying vehicles"],
        "avoid": [],
    },
    "Bharani": {
        "stars": 3,
        "label": "Moderate",
        "color": "#FF9800",
        "deity": "Yama (God of Death)",
        "nature": "Fierce (Ugra)",
        "ruling_planet": "Venus",
        "element": "Earth",
        "good_for": ["Endings and transformations", "Occult practices", "Agriculture"],
        "avoid": ["Marriage", "Starting new ventures", "Celebrations"],
    },
    "Krittika": {
        "stars": 4,
        "label": "Auspicious",
        "color": "#4CAF50",
        "deity": "Agni (Fire God)",
        "nature": "Sharp (Tikshna)",
        "ruling_planet": "Sun",
        "element": "Fire",
        "good_for": ["Spiritual practices", "Cutting ties", "Starting education", "Creative work"],
        "avoid": [],
    },
    "Rohini": {
        "stars": 5,
        "label": "Extremely Auspicious",
        "color": "#00C853",
        "deity": "Brahma (Creator)",
        "nature": "Fixed (Dhruva)",
        "ruling_planet": "Moon",
        "element": "Earth",
        "good_for": ["Marriage ceremonies", "Business ventures", "Property purchase", "Starting education", "All auspicious activities"],
        "avoid": [],
    },
    "Mrigashira": {
        "stars": 4,
        "label": "Auspicious",
        "color": "#4CAF50",
        "deity": "Chandra (Moon God)",
        "nature": "Soft (Mridu)",
        "ruling_planet": "Mars",
        "element": "Earth",
        "good_for": ["Marriage", "Travel", "Artistic work", "Buying clothes/jewelry"],
        "avoid": [],
    },
    "Ardra": {
        "stars": 2,
        "label": "Inauspicious",
        "color": "#D32F2F",
        "deity": "Rudra (Destroyer)",
        "nature": "Sharp (Tikshna)",
        "ruling_planet": "Rahu",
        "element": "Water",
        "good_for": ["Destruction of enemies", "Occult practices", "Research work"],
        "avoid": ["Marriage ceremonies", "Starting business", "House warming", "Important celebrations"],
    },
    "Punarvasu": {
        "stars": 4,
        "label": "Auspicious",
        "color": "#4CAF50",
        "deity": "Aditi (Mother of Gods)",
        "nature": "Movable (Chara)",
        "ruling_planet": "Jupiter",
        "element": "Water",
        "good_for": ["Marriage", "Starting business", "Travel", "Religious ceremonies"],
        "avoid": [],
    },
    "Pushya": {
        "stars": 5,
        "label": "Extremely Auspicious",
        "color": "#00C853",
        "deity": "Brihaspati (Jupiter)",
        "nature": "Light (Laghu)",
        "ruling_planet": "Saturn",
        "element": "Water",
        "good_for": ["All auspicious activities", "Marriage", "Business ventures", "Education", "Property purchase"],
        "avoid": [],
    },
    "Ashlesha": {
        "stars": 2,
        "label": "Inauspicious",
        "color": "#D32F2F",
        "deity": "Serpent (Naga)",
        "nature": "Sharp (Tikshna)",
        "ruling_planet": "Mercury",
        "element": "Water",
        "good_for": ["Occult practices", "Snake worship", "Dealing with enemies"],
        "avoid": ["Marriage", "Starting new ventures", "Important celebrations"],
    },
    "Magha": {
        "stars": 3,
        "label": "Moderate",
        "color": "#FF9800",
        "deity": "Pitris (Ancestors)",
        "nature": "Fierce (Ugra)",
        "ruling_planet": "Ketu",
        "element": "Water",
        "good_for": ["Ancestor worship", "Religious ceremonies", "Authority matters"],
        "avoid": ["Marriage of certain combinations"],
    },
    "Purva Phalguni": {
        "stars": 4,
        "label": "Auspicious",
        "color": "#4CAF50",
        "deity": "Bhaga (God of Fortune)",
        "nature": "Fierce (Ugra)",
        "ruling_planet": "Venus",
        "element": "Water",
        "good_for": ["Marriage", "Arts and entertainment", "Celebrations", "Social gatherings"],
        "avoid": [],
    },
    "Uttara Phalguni": {
        "stars": 5,
        "label": "Extremely Auspicious",
        "color": "#00C853",
        "deity": "Aryaman (God of Contracts)",
        "nature": "Fixed (Dhruva)",
        "ruling_planet": "Sun",
        "element": "Fire",
        "good_for": ["Marriage", "Business partnerships", "Contracts and agreements", "All auspicious activities"],
        "avoid": [],
    },
    "Hasta": {
        "stars": 5,
        "label": "Extremely Auspicious",
        "color": "#00C853",
        "deity": "Savitar (Sun God)",
        "nature": "Light (Laghu)",
        "ruling_planet": "Moon",
        "element": "Fire",
        "good_for": ["Marriage", "Business transactions", "Buying vehicles", "Crafts and arts", "All auspicious activities"],
        "avoid": [],
    },
    "Chitra": {
        "stars": 4,
        "label": "Auspicious",
        "color": "#4CAF50",
        "deity": "Vishwakarma (Divine Architect)",
        "nature": "Soft (Mridu)",
        "ruling_planet": "Mars",
        "element": "Fire",
        "good_for": ["Construction", "Arts and creativity", "Wearing new clothes", "Jewelry making"],
        "avoid": [],
    },
    "Swati": {
        "stars": 4,
        "label": "Auspicious",
        "color": "#4CAF50",
        "deity": "Vayu (Wind God)",
        "nature": "Movable (Chara)",
        "ruling_planet": "Rahu",
        "element": "Fire",
        "good_for": ["Trade and commerce", "Travel", "Education", "Business ventures"],
        "avoid": [],
    },
    "Vishakha": {
        "stars": 3,
        "label": "Moderate",
        "color": "#FF9800",
        "deity": "Indra-Agni (King of Gods & Fire)",
        "nature": "Sharp (Tikshna)",
        "ruling_planet": "Jupiter",
        "element": "Fire",
        "good_for": ["Achieving goals", "Competition", "Starting ventures"],
        "avoid": ["Marriage (requires careful consideration)"],
    },
    "Anuradha": {
        "stars": 4,
        "label": "Auspicious",
        "color": "#4CAF50",
        "deity": "Mitra (God of Friendship)",
        "nature": "Soft (Mridu)",
        "ruling_planet": "Saturn",
        "element": "Fire",
        "good_for": ["Marriage", "Friendships", "Travel", "Religious ceremonies"],
        "avoid": [],
    },
    "Jyeshtha": {
        "stars": 2,
        "label": "Inauspicious",
        "color": "#D32F2F",
        "deity": "Indra (King of Gods)",
        "nature": "Sharp (Tikshna)",
        "ruling_planet": "Mercury",
        "element": "Air",
        "good_for": ["Authority matters", "Protection rituals"],
        "avoid": ["Marriage", "Starting new ventures", "Celebrations"],
    },
    "Moola": {
        "stars": 2,
        "label": "Inauspicious",
        "color": "#D32F2F",
        "deity": "Nirriti (Goddess of Destruction)",
        "nature": "Sharp (Tikshna)",
        "ruling_planet": "Ketu",
        "element": "Air",
        "good_for": ["Endings and conclusions", "Research", "Occult practices"],
        "avoid": ["Marriage", "Starting new ventures", "Important celebrations"],
    },
    "Purva Ashadha": {
        "stars": 4,
        "label": "Auspicious",
        "color": "#4CAF50",
        "deity": "Apas (Water Goddess)",
        "nature": "Fierce (Ugra)",
        "ruling_planet": "Venus",
        "element": "Air",
        "good_for": ["Purification rituals", "Water-related activities", "Spiritual practices"],
        "avoid": [],
    },
    "Uttara Ashadha": {
        "stars": 5,
        "label": "Extremely Auspicious",
        "color": "#00C853",
        "deity": "Vishwadevas (Universal Gods)",
        "nature": "Fixed (Dhruva)",
        "ruling_planet": "Sun",
        "element": "Air",
        "good_for": ["Marriage", "Starting ventures", "All auspicious activities", "Leadership roles"],
        "avoid": [],
    },
    "Shravana": {
        "stars": 4,
        "label": "Auspicious",
        "color": "#4CAF50",
        "deity": "Vishnu (Preserver)",
        "nature": "Movable (Chara)",
        "ruling_planet": "Moon",
        "element": "Air",
        "good_for": ["Education", "Learning", "Travel", "Religious ceremonies"],
        "avoid": [],
    },
    "Dhanishta": {
        "stars": 3,
        "label": "Moderate",
        "color": "#FF9800",
        "deity": "Vasus (Gods of Wealth)",
        "nature": "Movable (Chara)",
        "ruling_planet": "Mars",
        "element": "Ether",
        "good_for": ["Music and arts", "Wealth accumulation", "Group activities"],
        "avoid": [],
    },
    "Shatabhisha": {
        "stars": 3,
        "label": "Moderate",
        "color": "#FF9800",
        "deity": "Varuna (God of Waters)",
        "nature": "Movable (Chara)",
        "ruling_planet": "Rahu",
        "element": "Ether",
        "good_for": ["Healing", "Medical treatment", "Research", "Mystical practices"],
        "avoid": [],
    },
    "Purva Bhadrapada": {
        "stars": 3,
        "label": "Moderate",
        "color": "#FF9800",
        "deity": "Aja Ekapada (One-footed Goat)",
        "nature": "Fierce (Ugra)",
        "ruling_planet": "Jupiter",
        "element": "Ether",
        "good_for": ["Spiritual practices", "Occult studies", "Transformation"],
        "avoid": ["Marriage (first half)"],
    },
    "Uttara Bhadrapada": {
        "stars": 5,
        "label": "Extremely Auspicious",
        "color": "#00C853",
        "deity": "Ahir Budhnya (Serpent of Depths)",
        "nature": "Fixed (Dhruva)",
        "ruling_planet": "Saturn",
        "element": "Ether",
        "good_for": ["Marriage", "Spiritual practices", "All auspicious activities", "Meditation and yoga"],
        "avoid": [],
    },
    "Revati": {
        "stars": 5,
        "label": "Extremely Auspicious",
        "color": "#00C853",
        "deity": "Pushan (Nourisher)",
        "nature": "Soft (Mridu)",
        "ruling_planet": "Mercury",
        "element": "Ether",
        "good_for": ["Marriage", "Travel", "Beginning journeys", "All auspicious activities", "Starting education"],
        "avoid": [],
    },
}

TITHI_QUALITIES = {
    "Pratipada": {"stars": 3, "label": "Moderate", "color": "#FF9800", "good_for": ["Starting new ventures", "Beginning education"], "avoid": ["Marriage"]},
    "Dwitiya": {"stars": 4, "label": "Auspicious", "color": "#4CAF50", "good_for": ["Marriage", "Religious ceremonies", "All good works"], "avoid": []},
    "Tritiya": {"stars": 5, "label": "Extremely Auspicious", "color": "#00C853", "good_for": ["Marriage", "Business", "Education", "Travel"], "avoid": []},
    "Chaturthi": {"stars": 3, "label": "Moderate", "color": "#FF9800", "good_for": ["Worship of Ganesha", "Removing obstacles"], "avoid": ["Long journeys"]},
    "Panchami": {"stars": 5, "label": "Extremely Auspicious", "color": "#00C853", "good_for": ["Marriage", "Education", "Religious ceremonies", "All auspicious activities"], "avoid": []},
    "Shashthi": {"stars": 3, "label": "Moderate", "color": "#FF9800", "good_for": ["War activities", "Competition"], "avoid": ["Marriage", "Peace activities"]},
    "Saptami": {"stars": 4, "label": "Auspicious", "color": "#4CAF50", "good_for": ["Marriage", "Travel", "Business transactions"], "avoid": []},
    "Ashtami": {"stars": 2, "label": "Inauspicious", "color": "#D32F2F", "good_for": ["Worship of fierce deities", "Protection rituals"], "avoid": ["Marriage", "Starting new ventures", "Celebrations"]},
    "Navami": {"stars": 3, "label": "Moderate", "color": "#FF9800", "good_for": ["Worship of Durga", "Strength building"], "avoid": ["Marriage in some traditions"]},
    "Dashami": {"stars": 4, "label": "Auspicious", "color": "#4CAF50", "good_for": ["Marriage", "Business", "Religious ceremonies"], "avoid": []},
    "Ekadashi": {"stars": 5, "label": "Highly Spiritual", "color": "#00C853", "good_for": ["Fasting", "Spiritual practices", "Worship of Vishnu"], "avoid": ["Material activities", "Consumption of grains"]},
    "Dwadashi": {"stars": 4, "label": "Auspicious", "color": "#4CAF50", "good_for": ["Breaking Ekadashi fast", "Religious ceremonies"], "avoid": []},
    "Trayodashi": {"stars": 3, "label": "Moderate", "color": "#FF9800", "good_for": ["Worship of Shiva (Pradosha)", "Spiritual practices"], "avoid": []},
    "Chaturdashi": {"stars": 2, "label": "Inauspicious", "color": "#D32F2F", "good_for": ["Worship of fierce deities", "Tantra practices"], "avoid": ["Marriage", "Important celebrations"]},
    "Purnima": {"stars": 5, "label": "Extremely Auspicious", "color": "#00C853", "good_for": ["All spiritual activities", "Meditation", "Religious ceremonies", "Charity"], "avoid": []},
    "Amavasya": {"stars": 2, "label": "New Moon", "color": "#D32F2F", "good_for": ["Ancestor worship", "Ending old things"], "avoid": ["Marriage", "Starting new ventures", "Celebrations"]},
}

def get_nakshatra_quality_data(nakshatra_name: str) -> Dict:
    return NAKSHATRA_QUALITIES.get(nakshatra_name, {
        "stars": 3, "label": "Moderate", "color": "#FF9800", "deity": "Unknown",
        "nature": "Variable", "ruling_planet": "Unknown", "element": "Unknown",
        "good_for": [], "avoid": []
    })

def get_tithi_quality_data(tithi_name: str) -> Dict:
    return TITHI_QUALITIES.get(tithi_name, {"stars": 3, "label": "Moderate", "color": "#FF9800", "good_for": [], "avoid": []})
