import {
  buildWhatsAppShareUrl,
  formatPanchangWhatsAppMessage,
} from '../utils/panchangWhatsAppMessage';

describe('panchangWhatsAppMessage', () => {
  const sample = {
    date: {
      gregorian: {
        date: '2026-08-25',
        day: 'Tuesday',
        formatted: 'Tuesday, 25 August, 2026',
      },
      hindu: {
        month: 'Bhadrapada',
        paksha: 'Shukla',
        samvatsara_name: 'Shobhana',
      },
    },
    location: { city: 'Bengaluru' },
    ayana: 'Dakshinayana',
    panchang: {
      tithi: {
        name: 'Ekadashi',
        paksha: 'Shukla',
        full_name: 'Shukla Ekadashi',
        end_time_formatted: '06:15 PM',
      },
      nakshatra: {
        name: 'Rohini',
        pada: 2,
        end_time_formatted: '09:40 AM',
      },
      yoga: { name: 'Siddhi', end_time_formatted: '11:20 AM' },
      karana: { current: 'Bava', end_time_formatted: '06:15 PM' },
      vara: { name: 'Tuesday', sanskrit: 'मंगलवार' },
    },
    inauspicious_times: {
      rahu_kaal: { start: '15:00:00', end: '16:30:00' },
      yamaganda: { start: '09:00:00', end: '10:30:00' },
      gulika: { start: '12:00:00', end: '13:30:00' },
    },
    auspicious_times: {
      abhijit_muhurat: { start: '11:48:00', end: '12:36:00' },
      brahma_muhurat: { start: '04:48:00', end: '05:36:00' },
    },
    south_india_special: [
      {
        english: 'Ekadashi Fasting',
        kannada: 'ಏಕಾದಶಿ ಉಪವಾಸ',
        sanskrit: 'एकादशी व्रतम्',
        text: 'Ekadashi Fasting | ಏಕಾದಶಿ ಉಪವಾಸ | एकादशी व्रतम्',
      },
    ],
  };

  it('builds a compact multilingual WhatsApp card from day data', () => {
    const message = formatPanchangWhatsAppMessage(sample);
    expect(message).toContain("Today's Panchang");
    expect(message).toContain('Samvatsara: Shobhana | ಶೋಭನ | शोभन');
    expect(message).toContain('Ayana: Dakshinayana | ದಕ್ಷಿಣಾಯನ | दक्षिणायन');
    expect(message).toContain('Masa: Bhadrapada | ಭಾದ್ರಪದ | भाद्रपद');
    expect(message).toContain('Tithi: Shukla Ekadashi');
    expect(message).toContain('ಏಕಾದಶಿ');
    expect(message).toContain('Rahu Kala:');
    expect(message).toContain('Yamaganda:');
    expect(message).toContain('Gulika Kala:');
    expect(message).toContain('Abhijit:');
    expect(message).toContain('Ekadashi Fasting');
    expect(message).toContain('Generated by MandirMitra · SanMitra Tech');
  });

  it('builds a WhatsApp share URL', () => {
    const url = buildWhatsAppShareUrl('hello');
    expect(url).toBe('https://wa.me/?text=hello');
  });
});
