name: vercel-staging-deploy

on:
  push:
    branches:
      - develop
    paths:
      - "frontend/**"
  workflow_dispatch:

concurrency:
  group: vercel-staging
  cancel-in-progress: true

env:
  VERCEL_ORG_ID: team_ZHtkRACAKbEAetS4cAw9jnzx
  VERCEL_PROJECT_ID: prj_SeLkzIY6Ll48BSCMHxavftQhQBOu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel staging
        working-directory: frontend
        run: vercel deploy --yes --token=${{ secrets.VERCEL_TOKEN }}
